"""Add age and budget to users

Revision ID: 22b30293cad2
Revises: 20251214151657
Create Date: 2025-12-14 21:49:10.301000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b30293cad2'
down_revision = '20251214151657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint('calendar_events_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('expenses_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('habit_logs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'habits', ['habit_id'], ['id'])

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_constraint('habits_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint('journal_entries_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))
        batch_op.drop_index('email')
        batch_op.drop_index('idx_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('idx_email', ['email'], unique=False)
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.drop_column('budget')
        batch_op.drop_column('age')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('journal_entries_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('habits_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('habit_logs_ibfk_1', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('expenses_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('calendar_events_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
