"""Add color and reminder fields to calendar_events

Revision ID: 4db631c7b28a
Revises: 7cb38c477f90
Create Date: 2025-12-14 12:30:58.120551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db631c7b28a'
down_revision = '7cb38c477f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reminder', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE calendar_events SET color = '#1a1a1a' WHERE color IS NULL")
    op.execute("UPDATE calendar_events SET reminder = 0 WHERE reminder IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('reminder')
        batch_op.drop_column('color')
    # ### end Alembic commands ###
